import{a as g,i as u,S as v}from"./assets/vendor-Rdv7LHNr.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();g.defaults.baseURL="https://pixabay.com/api/";const w="46457503-330abda4e6a20c9fb19d2e08a";let f=1;async function m(t,o=!1){o&&(f=1);try{const s=(await g("",{params:{key:w,q:t,page:f,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data;return s.totalHits>0?(f+=1,{hits:s.hits,totalHits:s.totalHits}):(u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3,color:"#FF0000",messageColor:"#FFFFFF"}),{hits:[],totalHits:0})}catch(a){return console.log(a),{hits:[],totalHits:0}}}const F=t=>t.map(({largeImageURL:o,webformatURL:a,tags:s,likes:e,views:r,comments:l,downloads:H})=>`<li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img
            class="gallery-image"
            src="${a}"
            alt="${s}"
          />
        </a>
        <div class="gallery-info">
          <p><b>Likes:</b> ${e}</p>
          <p><b>Views:</b> ${r}</p>
          <p><b>Comments:</b> ${l}</p>
          <p><b>Downloads:</b> ${H}</p>
        </div>
      </li>`).join(""),b=document.querySelector(".js-search-form"),d=document.querySelector(".js-gallery"),n=document.querySelector(".btn"),y=document.querySelector(".loader");let c="",h=0,i=0,L=new v(".js-gallery a");n.style.display="none";b.addEventListener("submit",S);let p=!0;async function S(t){if(t.preventDefault(),c=t.currentTarget.elements.user_query.value.trim(),c===""){u.error({message:"Please enter a valid search query.",position:"topRight",timeout:2e3,color:"#FF0000",messageColor:"#FFFFFF"});return}d.innerHTML="",y.style.display="block",n.style.display="none",i=0;try{const{hits:o,totalHits:a}=await m(c,!0);if(o.length>0){h=a,i+=o.length;const s=F(o);d.insertAdjacentHTML("beforeend",s),L.refresh(),i<h?n.style.display="block":u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:2e3,color:"lightblue",messageColor:"#FFFFFF"})}}catch(o){console.log(o)}finally{y.style.display="none",b.reset()}}n.addEventListener("click",q);async function q(){y.style.display="block";try{const{hits:t}=await m(c,!1);if(t.length>0){i+=t.length;const o=F(t);d.insertAdjacentHTML("beforeend",o),L.refresh()}p||P(),p=!1,i>=h&&(n.style.display="none",u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:2e3,color:"orange",messageColor:"#FFFFFF"}))}catch(t){console.log(t)}finally{y.style.display="none"}}function P(){const{height:t}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
