import{a as h,i as g,S as v}from"./assets/vendor-Rdv7LHNr.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();h.defaults.baseURL="https://pixabay.com/api/";const w="46457503-330abda4e6a20c9fb19d2e08a";let u=1;async function m(t,o=!1){o&&(u=1);try{const s=(await h("",{params:{key:w,q:t,page:u,per_page:15}})).data;return s.totalHits>0?(u+=1,{hits:s.hits,totalHits:s.totalHits}):(g.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3,color:"#FF0000",messageColor:"#FFFFFF"}),{hits:[],totalHits:0})}catch(a){return console.log(a),{hits:[],totalHits:0}}}const b=t=>t.map(({largeImageURL:o,webformatURL:a,tags:s,likes:e,views:r,comments:l,downloads:S})=>`<li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img
            class="gallery-image"
            src="${a}"
            alt="${s}"
          />
        </a>
        <div class="gallery-info">
          <p><b>Likes:</b> ${e}</p>
          <p><b>Views:</b> ${r}</p>
          <p><b>Comments:</b> ${l}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>`).join(""),F=()=>{new v(".gallery .gallery-item a",{captions:!0,captionsData:"alt",captionDelay:250,animationSpeed:300}).refresh()},L=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),n=document.querySelector(".btn"),d=document.querySelector(".loader");let y="",f=0,i=0;n.style.display="none";L.addEventListener("submit",q);let p=!0;async function q(t){t.preventDefault(),y=t.currentTarget.elements.user_query.value.trim(),c.innerHTML="",d.style.display="block",n.style.display="none",i=0;try{const{hits:o,totalHits:a}=await m(y,!0);if(o.length>0){f=a,i+=o.length;const s=b(o);c.insertAdjacentHTML("beforeend",s),F(),i<f?n.style.display="block":g.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:2e3,color:"lightblue",messageColor:"#FFFFFF"})}p||H(),p=!1}catch(o){console.log(o)}finally{d.style.display="none",L.reset()}}n.addEventListener("click",E);async function E(){d.style.display="block";try{const{hits:t}=await m(y,!1);if(t.length>0){i+=t.length;const o=b(t);c.insertAdjacentHTML("beforeend",o),F()}p||H(),i>=f&&(n.style.display="none",g.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:2e3,color:"orange",messageColor:"#FFFFFF"}))}catch(t){console.log(t)}finally{d.style.display="none"}}function H(){const{height:t}=c.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
